version: '3'
services:
  runner:
    image: crazynds/github-runner
    restart: unless-stopped
    volumes:
      - './data:/runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      URL: ${URL}
      TOKEN: ${TOKEN}
